import "./globals.css"
import {Inter} from "next/font/google"
import Head from "next/head";
import Providers from "@/app/_common/domain/contexts/providers";


const inter = Inter({subsets: ["latin"]})
// const akira = localFont({src: '/assets/fonts/akira/akira.otf',})

export const metadata = {
  title: "Talions films",
  description: "Generated by create next app",
}

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.className}>
    <Head>
      <title>Home App</title>
    </Head>
    <body className={inter.className}>

    <Providers>
      {children}
    </Providers>

    </body>
    </html>
  )
}
