import './globals.css'
import {Inter} from 'next/font/google'
import Head from "next/head";
import localFont from '@next/font/local'

// const inter = Inter({subsets: ['latin']})
const akira = localFont({src: '/assets/fonts/akira/akira.otf',})


export const metadata = {
  title: 'Talions films',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
  return (
    <html lang="en" className={akira.className}>
    <Head>
      <title>Home App</title>

    </Head>
    <body className={akira.className}>
    {children}
    </body>
    </html>
  )
}
